name: rpm
description: Remote Patient Monitoring

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.1.0
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.5
  firebase_storage: ^11.0.6
  flutter_svg: ^1.1.6
  flutter_local_notifications: ^12.0.4
  shared_preferences: ^2.0.15
  provider: ^6.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - lang/en.json
    - lang/si.json
    - assets/

  fonts:
    - family: Axiforma
      fonts:
       - asset: fonts/Axiforma-Thin.ttf
         weight: 200
       - asset: fonts/Axiforma-Regular.ttf
         weight: 300
       - asset: fonts/Axiforma-Medium.ttf
         weight: 400
       - asset: fonts/Axiforma-Semibold.ttf
         weight: 500
       - asset: fonts/Axiforma-Bold.ttf
         weight: 600
       - asset: fonts/Axiforma-ExtraBold.ttf
         weight: 700
       - asset: fonts/Axiforma-Heavy.ttf
         weight: 800
       - asset: fonts/Axiforma-Black.ttf
         weight: 900